# See https://github.com/hvr/multi-ghc-travis for more information.
sudo: true

language: c

services:
  - mongodb

addons:
  apt:
    packages:
    - libgmp-dev

env:
- ARGS="--resolver lts-6.2"
- ARGS="--resolver lts"
- ARGS="--resolver nightly"

matrix:
  allow_failures:
  - env: ARGS="--resolver nightly"


before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Install openstack client
- travis_retry sudo apt-get install python-pip
- sudo pip install python-openstackclient

script:
- stack $ARGS --no-terminal --install-ghc test --haddock
- stack $ARGS --no-terminal --install-ghc sdist
- stack $ARGS --no-terminal --install-ghc exec keystone&
- sleep 5
- cd tests
- ./run_openstack_tests.sh

cache:
  directories:
    - $HOME/.stack
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/92e3f35d91084ee2b8ce
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
